theme: jekyll-theme-cayman
title: Taylan's Journal
description: Description of the webpage. You can change from config.yml file.

[Assasment1]: (https://github.com/pjournal/mef04-taylan95/blob/gh-pages/Homework1_MD.Rmd)
